import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! })

export const generatethumbnails = async ({ user_prompt, aspectRatio }: { user_prompt: string, aspectRatio: string }) => {

    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: user_prompt,
        config: {
            responseModalities: ["IMAGE"],
            imageConfig: {
                aspectRatio: aspectRatio,
            },
            systemInstruction: "You are a professional YouTube Thumbnail Designer. Create high-contrast, vibrant, and click-worthy images with clear subjects and rule-of-thirds composition.",
        }
    })


    const part = response.candidates?.[0]?.content?.parts?.find(p => p.inlineData);

    if (!part?.inlineData) {
        throw new Error("No image was generated by the model.");
    }

    return {
        base64: part.inlineData.data,
        mimeType: part.inlineData.mimeType,
    };
}

