import { OpenRouter } from '@openrouter/sdk';

const openRouter = new OpenRouter({
    apiKey: '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',

});

export const generatethumbnails = async ({ user_prompt, aspectRatio }: { user_prompt: string, aspectRatio: string }) => {

    const completion = await openRouter.chat.send({
        model: 'xiaomi/mimo-v2-flash:free',
        messages: [
            {
                role: 'user',
                content: `${user_prompt}. IMPORTANT: Generate this in a ${aspectRatio} aspect ratio.`,
            },
        ],
        modalities: ["image"],
        stream: false,
    });

    const message = completion.choices[0]?.message as any;
    const imageDataUrl = message?.images?.[0]?.imageUrl?.url;


    if (!imageDataUrl) {
        throw new Error("no image was generated by model")
    }

    const matches = imageDataUrl.match(/^data:([^;]+);base64,(.+)$/);

    if (!matches || matches.length !== 3) {
        throw new Error("Invalid image format received.");
    }

    return {
        mimeType: matches[1],
        base64: matches[2],
    };


}





